### ISSUE TITLE
How to get started

### ISSUE THREAD

**Issue by xjsXjtu** [e8vm/e8vm#2]
Hi,
I am introduced to this project from Zhihu. This project seems like very interesting to me.
I am sorry I don't know how to comment/suggest in GitHub, so I new a issue here. Actually it's not an issue, but an improvement suggestion. 
readme.md just introduce what the project is, I guess there should be some doc/example code on how to get started, so as to get a concrete understanding on how the project runs, maybe even what the project architecture design is. 
Thanks. Nice to talk to you.

**Comment by h8liu** [comment]
Sorry but it is still under heavy construction; I should add some brief documents.

To start to play with it, you need to setup golang first (using the latest version). And then `go get -u lonnie.io/e8vm/...`. After installing you should be able to run `make` under `./t` directory, which compiles a single file `a.g`. Or under `./home` directory, which compiles all the testing packages underneath.

Some useful links:
[http://8k.lonnie.io/] for the dependency graph, which is automatically generated by [https://github.com/h8liu/e8tools].
[https://gowalker.org/lonnie.io/e8vm] for the golang doc of course.
[http://lonnie.io/asmplay/] for the assembly playground, which source code is here [https://github.com/h8liu/asmplay].

- `arch8` package is the simulator.
- `link8` is a simple linker
- `asm8/*` are packages for the assembler
- `dasm8` is the deassembler package.
- `build8` is a general building and linking framework
- `lex8` provides a lexing framework, it is shared between the assembler and the language parser.
- `fmt8` are helper packages for formatting. It contains a `io.Writer` that can print indentation.
- Most other packages belong to the compiler that I am currently writing -- parsing, symbols, ast, ir. The package names should explain their contents. I call the language **g** because it is by-n-large a golang subset.

To use the makefile that comes with the project, you also need to install `e8tools`, `golint` and `gotags`:

`go get -u lonnie.io/e8tools/...`
`go get -u github.com/golang/lint/golint`
`go get -u github.com/jstemmer/gotags`

You need `e8tools` for the `e8chk` binary, which checks if the source file has less than 300 lines, less than 80 chars per line (tab count as 4 chars), and most importantly, it checks if the entire project does not have circular dependencies among files. (I really should add the circ-dep check into travis-ci.)

Hope this might help.
