### ISSUE TITLE
Decouple semantics pass from IR gen

### ISSUE THREAD

**Issue by h8liu** [e8vm/e8vm#33]
So that Krystal can start enhance our IR engine.

**Comment by h8liu** [comment]
This is also to develop a basis for static analyses. For example, for building the index for the code search engine, it does not need to execute the IR gen pass, but only the semantics pass.

**Comment by h8liu** [comment]
To @rednaxelafx 

As we discussed, one way to do it is to have types and symbol table fields added into the current ast nodes. However, I tried and do not really like that approach. The current ast data structure is a clean version that stores the parsing results, and adding types will put `g8/types` package as a dependency of `g8/ast`, which does not make very much sense. It would be nice if `g8/ast` can be kept as clean as possible as just the parsing result.

So @rednaxelafx , do you really need the typed AST to be isomorphic to the parsing AST? Or you basically just want a typed "IR" like tree? For example, I guess you probably do not care about the ParenExpr (an expression wrapped by parenthesis) at all. Or in other words, do you mind if we structure the passes like this:

`text` --(parsing)--> `ast` --(static analysis)--> `typed ir` --(ir gen)--> `untyped ir` --(code gen)--> asm

and you can take over all the parts after `typed ir`. The `typed ir` will preserve the control flow structure (`if` and `for` statements), rather than using basic blocks, but will not losslessly reflect the origin program's ast (like the parenthesis's will be dropped).

I am also looking for a better word for `typed ir`. I find the term `asg`: https://en.wikipedia.org/wiki/Abstract_semantic_graph , but not sure if it is the right word.

So @rednaxelafx , please tell me how you think about it.

**Comment by rednaxelafx** [comment]
Hey @h8liu 

The input I'd like to have for generating my IR is one that:
 * does not have to be the same AST as what the parser generates; it might be desirable to keep the AST immutable anyway.
 * has done full type checking and other semantic analysis on the source language level, so that I don't _have to_ do additional semantic validation while generating my IR (but of course for development purposes I might still add asserts just in case).
 * does not care about anything related to concrete syntax. Take your ParenExpr for example, if this node merely records the fact that there's a pair of parenthesis around an expression, then I don't need that kind of detail; but, if what it really means is "for the expression (e1; e2; e3), evaluate all of e1, e2 and e3 for their side effects, but use the value of e3 as the value of this parenthesized expression", then that's significant, and I'd like to have that information when I generate IR. This kind of node is usually called a "StatementExpression", or "StmtExpr" for short, which means it (1) is an expression for that it computes to a value, and (2) it's backed by statements for their side-effects.
 * keeps the high-level control-flow structure. Specifically, please keep control flow structures related to loops, so that I can easily identify loop headers without having to compute dominance information first. This is the good thing about designing a programming language to conform to the ideas of "structural programming" - there would be no irreducible control flow in the program, which greatly simplifies a lot of things, e.g. efficient SSA construction.

As long as the properties above are all met, I'm fine with any format of IR you give me :-)

**Comment by h8liu** [comment]
Awesome. I will start working on this now. Hopefully this can be done in 10 days.

**Comment by rednaxelafx** [comment]
By the way, regarding "Abstract Semantic Graph", I don't think it's a good fit for this "typed AST" that you're taking on. Calling it "typed AST" should be good enough.

**Comment by h8liu** [comment]
Typed AST it is then.

How about scopes and symbol tables? Should I also store the symbol table in the typed ast along with scopes? And maybe also the symbol each identifier is referencing to?

**Comment by h8liu** [comment]
The expression part is done. Now working on the statement parts.

**Comment by h8liu** [comment]
Statement part also done, need to think about all the top level declarations now.

**Comment by h8liu** [comment]
This is mostly done. semantic pass is in `g8/sempass` package now.

There might be some old boilerplate code here and there, but should be easy to clean up in the future.
